import uk.gov.hmrc.DefaultBuildSettings

val appName = "submission-consolidator"

lazy val IntegrationTest = config("it") extend (Test)

ThisBuild / majorVersion := 0
ThisBuild / scalaVersion := "2.13.16"

lazy val microservice = Project(appName, file("."))
  .enablePlugins(
    play.sbt.PlayScala,
    SbtDistributablesPlugin
  )
  .settings(
    organization := "uk.gov.hmrc",
    PlayKeys.playDefaultPort := 9198,
    scalafmtOnCompile := true,
    libraryDependencies ++= AppDependencies.compile ++ AppDependencies.test,
    scalacOptions ++= Seq(
      "-Xfatal-warnings",
      "-Xlint:-missing-interpolator,-byname-implicit,_",
      "-Ywarn-numeric-widen",
      //"-Ywarn-value-discard",
      //"-Ywarn-dead-code",
      "-deprecation",
      "-feature",
      "-unchecked",
      "-language:higherKinds",
      // silence all warnings on autogenerated files
      "-Wconf:src=routes/.*:silent"
    ),
    routesImport ++= Seq(
      "consolidator.repositories.NotificationStatus",
      "consolidator.repositories.CorrelationId",
      "common.ValueClassBinder._"
    )
  )

lazy val it = project
  .enablePlugins(play.sbt.PlayScala)
  .dependsOn(microservice % "test->test")
  .settings(
    DefaultBuildSettings.itSettings(),
    scalafmtOnCompile := true,
    scalacOptions ++= Seq(
      "-Xfatal-warnings",
      "-Xlint:-missing-interpolator,-byname-implicit,_",
      "-Ywarn-numeric-widen",
      //"-Ywarn-value-discard",
      //"-Ywarn-dead-code",
      "-deprecation",
      "-feature",
      "-unchecked",
      "-language:higherKinds",
      // silence all warnings on autogenerated files
      "-Wconf:src=routes/.*:silent"
    ),
  )
